
DROP TABLE PERMISSIONS;
DROP TABLE DEPARTMENTS;
DROP TABLE USERS;
DROP TABLE BREAKERS;
DROP TABLE RECORDS;

CREATE TABLE IF NOT EXISTS PERMISSIONS(
    ID INTEGER NOT NULL PRIMARY KEY,
    PERMISSION TEXT
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS(
    ID INTEGER NOT NULL PRIMARY KEY,
    DEPARTMENT_CODE TEXT NOT NULL,
    TYPE TEXT
);

CREATE TABLE IF NOT EXISTS USERS(
    ID INTEGER NOT NULL PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    ID_PERMISSION INT NOT NULL,
    ID_DEPARTMENT INT NOT NULL,
    FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSIONS (ID),
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENTS (ID)
);

CREATE TABLE IF NOT EXISTS BREAKERS(
    ID TEXT NOT NULL,
    DEVICE_NAME TEXT NOT NULL,
    ID_USER INT NOT NULL,
    DEVICE_TYPE TEXT,
    FOREIGN KEY (ID_USER) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS RECORDS(
    ID INTEGER NOT NULL PRIMARY KEY,
    ID_BREAKER TEXT NOT NULL,
    KWH INT NOT NULL,
    TEMP INT NOT NULL,
    RECORD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_BREAKER) REFERENCES BREAKERS (ID)
);

SELECT * FROM PERMISSIONS;